const ASSET='https://raw.githubusercontent.com/falcoer/flowtherapy-animation-website/main/assets/';
const icons={instagram:'◎',youtube:'▶'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(config){const {site,hero,navigation,socials,about,press}=config;document.title=`${site.name} — ${hero.lines.join(' ')}`;document.querySelector('#app').innerHTML=`
<header id="accueil" class="home">
  <nav class="nav"><img class="logo" src="${ASSET}ChatGPT%20Image%2028%20mars%202026%20%C3%A0%2022_18_28.png" alt="Flow Therapy"><div class="links">${navigation.map(n=>`<a href="${n.href}">${esc(n.label)}</a>`).join('')}</div><div class="tools"><button id="qr-open" class="icon-btn" aria-label="Partager par QR code">▦</button><button id="theme" class="theme" aria-label="Changer de thème"><span>☀</span><span>☾</span></button></div></nav>
  <div class="hero-grid"><div class="copy"><h1>${hero.lines.map((l,i)=>`<span class="line l${i+1}">${esc(l)}</span>`).join('')}</h1><p>${esc(site.tagline)}</p><div class="actions"><a class="primary" href="${socials[1].url}" target="_blank" rel="noopener">▶ ÉCOUTER</a><a class="secondary" href="#presse">PRESSE</a></div></div>
  <div class="art"><div class="watermark"></div><div class="alpacas"><img src="${ASSET}alpaga1.png" alt=""><img src="${ASSET}alpaga2.png" alt=""><img src="${ASSET}alpaga3.png" alt=""></div><div class="brush">${esc(hero.signature)}</div><div class="socials">${socials.map(s=>`<a class="social ${s.icon}" href="${s.url}" target="_blank" rel="noopener" aria-label="${s.label}">${icons[s.icon]}</a>`).join('')}</div></div></div>
</header>
<section id="groupe" class="section"><p class="kicker">${esc(site.location)}</p><h2>${esc(about.title)}</h2><div class="prose">${about.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div></section>
<section id="presse" class="section"><p class="kicker">Actualités & reconnaissance</p><h2>${esc(press.title)}</h2><div class="press-grid">${press.items.map(x=>`<a class="press-card" href="${x.url}" target="_blank" rel="noopener"><small>${esc(x.source)}</small><strong>${esc(x.title)}</strong><span>Consulter ↗</span></a>`).join('')}</div></section>
<footer id="contact"><strong>Flow Therapy</strong><span>${esc(site.copyright)}</span>${socials.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${s.label}</a>`).join('')}</footer>`;setupTheme();setupQr(site.url)}
function setupTheme(){const b=document.querySelector('#theme');const saved=localStorage.getItem('ft-theme');if(saved)document.documentElement.dataset.theme=saved;b.onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('ft-theme',next)}}
function setupQr(url){const d=document.querySelector('#qr-dialog'),o=document.querySelector('#qr-open'),c=document.querySelector('#qr-close'),t=document.querySelector('#qr-code');document.querySelector('#qr-url').textContent=url;let done=false;o.onclick=()=>{if(!done&&window.QRCode){new QRCode(t,{text:url,width:280,height:280,correctLevel:QRCode.CorrectLevel.H});done=true}d.showModal();requestAnimationFrame(()=>d.classList.add('is-open'))};const close=()=>{d.classList.remove('is-open');setTimeout(()=>d.close(),180)};c.onclick=close;d.onclick=e=>{if(e.target===d)close()}}
fetch('config/site.json',{cache:'no-store'}).then(r=>r.json()).then(render).catch(e=>{console.error(e);document.querySelector('#app').innerHTML='<p class="error">Le contenu du site ne peut pas être chargé.</p>'});