const ASSET='assets/';
const icons={instagram:'◎',youtube:'▶'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(config){const {site,hero,navigation,socials,about,press}=config;const listen=socials.find(s=>s.icon==='youtube')?.url||socials[0]?.url||'#contact';document.title=`${site.name} — ${hero.lines.join(' ')}`;document.querySelector('#app').innerHTML=`
<header id="accueil" class="home">
  <nav class="nav" aria-label="Navigation principale"><a href="#accueil" aria-label="Accueil Flow Therapy"><img class="logo" src="assets/logo.jpg" alt="Flow Therapy"></a><div class="links">${navigation.map(n=>`<a href="${n.href}">${esc(n.label)}</a>`).join('')}</div><div class="tools"><button id="qr-open" class="icon-btn" type="button" aria-label="Partager par QR code">▦</button><button id="theme" class="theme" type="button" aria-label="Activer le thème sombre" aria-pressed="false"><span aria-hidden="true">☀</span><span aria-hidden="true">☾</span></button></div></nav>
  <div class="hero-grid"><div class="copy"><h1>${hero.lines.map((l,i)=>`<span class="line l${i+1}">${esc(l)}</span>`).join('')}</h1><p>${esc(site.tagline)}</p><div class="actions"><a class="primary" href="${listen}" target="_blank" rel="noopener">▶ ÉCOUTER</a><a class="secondary" href="#presse">PRESSE</a></div></div>
  <div class="art" aria-label="Composition graphique Flow Therapy"><div class="watermark" aria-hidden="true"></div><div class="alpacas" aria-hidden="true">${[1,2,3].map(n=>`<div class="alpaca"><img class="alpaca-nude" src="${ASSET}alpaga${n}-nu.png" alt=""><img class="alpaca-costumed" src="${ASSET}alpaga${n}.png" alt=""></div>`).join('')}</div><div class="brush">${esc(hero.signature)}</div><div class="socials">${socials.map(s=>`<a class="social ${s.icon}" href="${s.url}" target="_blank" rel="noopener" aria-label="${esc(s.label)}">${icons[s.icon]||esc(s.label[0])}</a>`).join('')}</div></div></div>
</header>
<section id="groupe" class="section"><p class="kicker">${esc(site.location)}</p><h2>${esc(about.title)}</h2><div class="prose">${about.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div></section>
<section id="presse" class="section"><p class="kicker">Actualités & reconnaissance</p><h2>${esc(press.title)}</h2><div class="press-grid">${press.items.map(x=>`<a class="press-card" href="${x.url}" target="_blank" rel="noopener"><small>${esc(x.source)}</small><strong>${esc(x.title)}</strong><span>Consulter ↗</span></a>`).join('')}</div></section>
<footer id="contact"><strong>Flow Therapy</strong><span>${esc(site.copyright)}</span>${socials.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${esc(s.label)}</a>`).join('')}</footer>`;setupTheme();setupQr(site.url);setupAlpacaReveal()}
function setupAlpacaReveal(){const group=document.querySelector('.alpacas');if(!group||matchMedia('(prefers-reduced-motion: reduce)').matches){group?.classList.add('is-costumed');return}requestAnimationFrame(()=>requestAnimationFrame(()=>group.classList.add('is-costumed')))}
function setupTheme(){const button=document.querySelector('#theme'),meta=document.querySelector('meta[name="theme-color"]');let theme=localStorage.getItem('ft-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');const apply=()=>{document.documentElement.dataset.theme=theme;button.setAttribute('aria-pressed',String(theme==='dark'));button.setAttribute('aria-label',theme==='dark'?'Activer le thème clair':'Activer le thème sombre');meta.content=theme==='dark'?'#07101d':'#fbf8f2'};apply();button.onclick=()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem('ft-theme',theme);apply()}}
function setupQr(url){const d=document.querySelector('#qr-dialog'),o=document.querySelector('#qr-open'),c=document.querySelector('#qr-close'),t=document.querySelector('#qr-code');document.querySelector('#qr-url').textContent=url;let done=false;const close=()=>{d.classList.remove('is-open');setTimeout(()=>{if(d.open)d.close()},180)};o.onclick=()=>{if(!done&&window.QRCode){new QRCode(t,{text:url,width:280,height:280,correctLevel:QRCode.CorrectLevel.H});done=true}d.showModal();requestAnimationFrame(()=>d.classList.add('is-open'));c.focus()};c.onclick=close;d.onclick=e=>{if(e.target===d)close()};d.addEventListener('cancel',e=>{e.preventDefault();close()})}
fetch('config/site.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Configuration indisponible (${r.status})`);return r.json()}).then(render).catch(e=>{console.error(e);document.querySelector('#app').innerHTML='<p class="error">Le contenu du site ne peut pas être chargé.</p>'});